run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
name: pages deployer
branding:
  icon: 'activity'  
  color: 'blue'
on:
  workflow_dispatch:
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: latest
          run_install: true

      - name: build
        run: "pnpm build-only"
